/**
 * Chapter Types
 * 
 * Represents a chapter/segment within a story.
 * Each chapter contains narration, optional dialogue, audio, and interactive choices.
 */

import type { Choice } from './choice';

export interface Chapter {
  /** Unique identifier for the chapter */
  id: string;
  
  /** Reference to parent Story ID */
  storyId: string;
  
  /** Chapter sequence number (1-indexed) */
  chapterNumber: number;
  
  /** Main narration text generated by AI */
  narration: string;
  
  /** Optional character dialogue (if characters are speaking) */
  dialogue?: string;
  
  /** Character name speaking the dialogue */
  speaker?: string;
  
  /** URL to audio file (ElevenLabs TTS output) */
  audioUrl?: string;
  
  /** Audio duration in seconds */
  audioDurationSeconds?: number;
  
  /** Whether this chapter contains a decision point */
  isDecisionPoint: boolean;
  
  /** Available choices for the user at this chapter */
  choices: Choice[];
  
  /** Choice ID that was selected by user (if decision was made) */
  selectedChoiceId?: string;
  
  /** Timestamp when chapter was created/generated */
  timestamp: Date;
  
  /** Timestamp when user started this chapter */
  startedAt?: Date;
  
  /** Timestamp when user finished this chapter */
  completedAt?: Date;
  
  /** Scene description for visual generation (future feature) */
  sceneDescription?: string;
  
  /** Scene image URL (if generated) */
  sceneImageUrl?: string;
  
  /** Emotional tone of the chapter */
  emotionalTone?: 'happy' | 'sad' | 'exciting' | 'calm' | 'tense' | 'mysterious';
  
  /** Background music recommendation */
  suggestedMusicTheme?: string;
}

/**
 * Request type for generating next chapter via Gemini AI
 */
export interface GenerateChapterRequest {
  storyId: string;
  previousChapters: Chapter[];
  selectedChoice?: Choice;
  userInput?: string; // Optional voice/text input from child
  language: 'id' | 'en';
  ageGroup: 'toddler' | 'kid' | 'preteen';
}

/**
 * Response type from Gemini AI for chapter generation
 */
export interface GenerateChapterResponse {
  narration: string;
  dialogue?: string;
  speaker?: string;
  isDecisionPoint: boolean;
  choices: Array<{
    text: string;
    consequence: string;
    moralValue?: string;
  }>;
  sceneDescription?: string;
  emotionalTone?: Chapter['emotionalTone'];
  suggestedMusicTheme?: string;
}
